title: DVC Science Alliance
email: secretary@dvcsciencealliance.org
description: Home of the DVC Science Alliance, a consortium of STEM clubs at Diablo Valley College seeking to utilize science to better understand the world around us.
baseurl: ""
url: "https://dvcsciencealliance.org"
